name = "submix"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Pages specific configuration
[env.production]
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[env.preview]
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
