name = "submix"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[env.production]
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]